apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: greeting-service
build:
  artifacts:
    - image: perrinsjason/demo-greeting-service
      context: .
      jib: {}
deploy:
  statusCheckDeadlineSeconds: 300
  kubectl:
    manifests:
      - k8s/*
