name: Manual Release

on: 
  workflow_dispatch:
    inputs:
      release:
        version: 'Version'     
        required: true
        default: '1.0.0'
      tags:
        description: 'Release'  


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 14
          server-id: github
      - name: Prepare and perform release
        run: mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Rollback if failure
        if: ${{ failure() }}
        run: mvn --batch-mode release:rollback
